import MySQLdb
conn=MySQLdb.connect()
import tkinter as tk
def insertdata():
    btn1.config(state="normal")
    btn2.config(state="normal")
def cofirminsert():
    id = int(e1.get())
    name = e2.get()
    salary = float(e3.get())

x=tk.Tk()
x.geometry("500x500")
l1=tk.Label(text="Emp id:")
e1=tk.Entry()
l2=tk.Label(text="Emp name:")
e2=tk.Entry()
l3=tk.Label(text="Emp Salary:")
e3=tk.Entry()
b1=tk.Button(text="Insert",command=insertdata)
b2=tk.Button(text="Update")
b3=tk.Button(text="Delete")
btn1=tk.Button(text="Confirm")
btn2=tk.Button(text="Clear")
btn3=tk.Button(text="Confirm")
btn4=tk.Button(text="Clear")
btn5=tk.Button(text="Confirm")
btn6=tk.Button(text="Cancel")
l1.grid(row=0,column=0)
e1.grid(row=0,column=1)
l2.grid(row=1,column=0)
e2.grid(row=1,column=1)
l3.grid(row=2,column=0)
e3.grid(row=2,column=1)
b1.grid(row=3, column=0, padx=(0, 20))
b2.grid(row=3, column=1, padx=(0, 20))
b3.grid(row=3, column=2)
btn1.grid(row=4,column=0)
btn2.grid(row=4,column=1)
btn3.grid(row=4,column=2)
btn4.grid(row=4,column=3)
btn5.grid(row=4,column=4)
btn6.grid(row=4,column=5)
btn1.config(state="disabled")
btn2.config(state="disabled")
btn3.config(state="disabled")
btn4.config(state="disabled")
btn5.config(state="disabled")
btn6.config(state="disabled")
x.mainloop()